openapi: 3.0.0
info:
  title: EKS Cluster Management API
  version: 1.0.0
servers:
  - url: https://eks.example.com
paths:
  /clusters/restore:
    post:
      summary: Generate backup for EKS clusters
      operationId: RestoreEKSClusters

      description: |
        Restore the EKS clusters.
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/ClusterRestoreRequest"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SSMLambdaResponse"
        "500":
          description: Exception occurred while starting automation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SSMErrorLambdaResponse"

components:
  schemas:
    SSMLambdaResponse:
      type: object
      properties:
        apiPath:
          type: string
          description: The path to the API operation.
        httpMethod:
          type: string
          default: get
          description: The method of the API operation.
        httpStatusCode:
          type: integer
          default: 200
          description: The path to the API operation.
        responseBody:
          type: object
          properties:
            json:
              type: object
              properties:
                executionId:
                  type: string
                  description: ID of the SSM automation execution.

    SSMErrorLambdaResponse:
      type: object
      properties:
        apiPath:
          type: string
          description: The path to the API operation.
        httpMethod:
          type: string
          default: get
          description: The method of the API operation.
        httpStatusCode:
          type: integer
          default: 500
          description: The path to the API operation.
        responseBody:
          type: object
          properties:
            json:
              type: object
              properties:
                exception:
                  type: string
                  description: Error message.

    ClusterRestoreRequest:
      type: object
      required:
        - accountId
        - region
        - clusterName
        - restoreOptions
        - backupName
      properties:
        accountId:
          type: string
          description: AWS Account ID.
        region:
          type: string
          description: AWS Region.
        clusterName:
          type: string
          description: EKS Cluster Name.
        restoreOptions:
          type: object
          properties:
            backupName:
              type: string
              description: Name of the velero backup which needs to be restored.
